title: Foggy Labs
description: Independent iOS app studio
theme: minima
baseurl: ""
url: "https://foggy-labs.github.io"

header_pages:
  - index.md

plugins:
  - jekyll-sitemap

# Exclude build artifacts from sitemap
exclude:
  - README.md
  - _templates/
